---
abstract: 'Calculate exposure value (EV)'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::More: '0.94'
  perl: '5.020000'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.020000'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Photography-EV
requires:
  base: '0'
  perl: '5.020000'
resources:
  bugtracker: https://github.com/plicease/Photography-EV/issues
  homepage: http://perl.wdlabs.com/Photography-EV
  repository: git://github.com/plicease/Photography-EV.git
version: '0.05'
